services:
  - type: web
    name: ncs-simulator
    runtime: node
    plan: free
    buildCommand: npm install && node data/seed.js
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
